### ISSUE TITLE
Refactoring working_dir name

### ISSUE THREAD

**Issue by sho-tanaka0210** [Mizukichi0210/Manage-Entered-and-Left-on-Discord#7]
```yml
version: '3'
services:
  bot:
    build: .
    container_name: 'discord_test'
    tty: true
    # This one
    working_dir: '/discord_test/src'
    volumes:
      - './src:/discord_test/src'
```
